version: '3'

services:

  postgres:
    container_name: postgres-container
    build:
      context: .
      dockerfile: ./images/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P0stgres
      - POSTGRES_DB=tourreserve
    ports:
      - "5432:5432"

  maven:
    container_name: maven-container
    build:
      context: .
      dockerfile: ./images/maven/Dockerfile
    tty: true
    volumes:
      - ./terasoluna-app:/home/root/terasoluna-app

  tomcat:
    container_name: tomcat-container
    image: tomcat:9.0.30-jdk8-openjdk-slim
    volumes:
      - ./terasoluna-app:/root/terasoluna-app
    ports:
      - "8080:8080"
