apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: terasoluna-summer
  labels:
    app: terasoluna
    release: summer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: terasoluna
      release: summer
  template:
    metadata:
      labels:
        app: terasoluna
        release: summer
    spec:
      containers:
      - name: httpd-container
        image: muroya/td_httpd:1.0
        ports:
        - containerPort: 80
      - name: tomcat-container
        image: muroya/td_tomcat:1.0
        env:
        ports:
        - containerPort: 8009
      - name: alpine-container
        image: muroya/td_alpine:1.0
        tty: true

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: terasoluna-winter
  labels:
    app: terasoluna
    release: winter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: terasoluna
      release: winter
  template:
    metadata:
      labels:
        app: terasoluna
        release: winter
    spec:
      containers:
      - name: httpd-container
        image: muroya/td_httpd:1.0
        ports:
        - containerPort: 80
      - name: tomcat-container
        image: muroya/td_tomcat:1.0
        env:
        ports:
        - containerPort: 8009
      - name: alpine-container
        image: muroya/td_alpine:1.0
        tty: true
