apiVersion: v1
kind: Service
metadata:
  name: terasoluna
  labels:
    app: terasoluna
spec:
  selector:
    app: terasoluna
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer