apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
  labels:
    service: kibana
spec:
  type: NodePort
  selector:
    run: kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: http
    nodePort: 30050

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
      - name: kibana-container
        image: kibana:5.6
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP