version: '3'

services:

  postgres:
    container_name: postgres-container
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P0stgres
      - POSTGRES_DB=tourreserve
    ports:
      - "5432:5432"
